// Script uses dates generated by dateStyle.js

var profileImage = document.getElementById("profileImage");
switch (year)
{
    default:
        switch (month)
        {
            default:
                break;
            case 9: // October
                switch (day)
                {
                    default:
                        profileImage.src = "Img/Profile.png";
                        break;
                    case 1: // Birthday
                        break;
                    case 31: // Halloween
                        profileImage.src = "Img/HalloweenProfile.png";
                }
        }
        break;
}